name: Fix PHP code style issues

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@1.0.0
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'PHP CS Fixer'
